package com.simonecompany.lavagna.ui

import androidx.compose.runtime.staticCompositionLocalOf

/**
 * Traduzioni it/en estratte dalla web app (stesse chiavi di index.html).
 */
object Strings {

    enum class Lang { IT, EN }

    private val italian = mapOf(
        "title" to "Lavagna",
        "pointer" to "Puntatore",
        "pen" to "Penna",
        "eraser" to "Gomma",
        "shapes" to "Forme",
        "color" to "Colore",
        "thickness" to "Spessore:",
        "zoom" to "Zoom",
        "clear" to "Pulisci",
        "new" to "Nuova",
        "pages" to "Pagine",
        "pagesBoard" to "Pagine Lavagna",
        "newPage" to "Nuova Pagina",
        "clearAll" to "Cancella Tutto",
        "shapes2D" to "Figure 2D",
        "shapes3D" to "Figure 3D",
        "eraserType" to "Tipo di Gomma",
        "eraserNormalFull" to "Gomma Normale",
        "eraserStrokeFull" to "Cancella Tratto Intero",
        "eraserLassoFull" to "Lazo Selettivo",
        "eraserNormal" to "Normale",
        "eraserStroke" to "Tratto",
        "eraserLasso" to "Lazo",
        "pointerType" to "Tipo di Puntatore",
        "pointerNormalFull" to "Puntatore Normale",
        "pointerLassoFull" to "Lazo Selettivo",
        "pointerNormal" to "Normale",
        "pointerLasso" to "Lazo",
        "confirm" to "Conferma",
        "cancel" to "Annulla",
        "page" to "Pagina",
        "shape_rect" to "Rettangolo",
        "shape_square" to "Quadrato",
        "shape_circle" to "Cerchio",
        "shape_ellipse" to "Ellisse",
        "shape_line" to "Linea",
        "shape_arrow" to "Freccia",
        "shape_triangle" to "Triangolo",
        "shape_rightTriangle" to "Triangolo Rettangolo",
        "shape_star" to "Stella",
        "shape_star4" to "Stella 4 Punte",
        "shape_star6" to "Stella 6 Punte",
        "shape_heart" to "Cuore",
        "shape_diamond" to "Rombo",
        "shape_parallelogram" to "Parallelogramma",
        "shape_trapezoid" to "Trapezio",
        "shape_pentagon" to "Pentagono",
        "shape_hexagon" to "Esagono",
        "shape_heptagon" to "Ettagono",
        "shape_octagon" to "Ottagono",
        "shape_nonagon" to "Ennagono",
        "shape_decagon" to "Decagono",
        "shape_cross" to "Croce",
        "shape_cube" to "Cubo",
        "shape_cuboid" to "Parallelepipedo",
        "shape_cylinder" to "Cilindro",
        "shape_cone" to "Cono",
        "shape_pyramid" to "Piramide",
        "shape_sphere" to "Sfera",
        "clearPageTitle" to "Pulisci Pagina",
        "clearPageMsg" to "Sei sicuro di voler pulire la pagina corrente?",
        "deletePageTitle" to "Elimina Pagina",
        "deletePageMsg" to "Vuoi eliminare la",
        "clearAllTitle" to "Cancella Tutto",
        "clearAllMsg" to "Sei sicuro di voler cancellare tutte le pagine e ripartire da una nuova?",
        "clearSingleTitle" to "Pulisci Pagina",
        "clearSingleMsg" to "Vuoi cancellare tutto il contenuto della Pagina 1?",
        "colorDefault" to "Predefiniti",
        "colorCustom" to "Personalizzato",
        "toolText" to "Testo",
        "toolFill" to "Riempimento",
        "toolBg" to "Sfondo",
        "textOptions" to "Opzioni Testo",
        "size" to "Dim.",
        "save" to "Salva",
        "saveTitle" to "Salva Lavagna",
        "saveMsg" to "Nome file e formato:",
        "ctxDup" to "Duplica",
        "ctxFront" to "Porta in primo piano",
        "ctxBack" to "Porta in fondo",
        "ctxDel" to "Elimina",
        "backgrounds" to "Sfondi",
        "backgroundSettings" to "Impostazioni sfondo",
        "colors2" to "Colori",
        "patterns2" to "Sfondi",
        "none" to "Nessuno"
    )

    private val english = mapOf(
        "title" to "Whiteboard",
        "pointer" to "Pointer",
        "pen" to "Pen",
        "eraser" to "Eraser",
        "shapes" to "Shapes",
        "color" to "Color",
        "thickness" to "Thickness:",
        "zoom" to "Zoom",
        "clear" to "Clear",
        "new" to "New",
        "pages" to "Pages",
        "pagesBoard" to "Board Pages",
        "newPage" to "New Page",
        "clearAll" to "Clear All",
        "shapes2D" to "2D Shapes",
        "shapes3D" to "3D Shapes",
        "eraserType" to "Eraser Type",
        "eraserNormalFull" to "Normal Eraser",
        "eraserStrokeFull" to "Delete Whole Stroke",
        "eraserLassoFull" to "Selective Lasso",
        "eraserNormal" to "Normal",
        "eraserStroke" to "Stroke",
        "eraserLasso" to "Lasso",
        "pointerType" to "Pointer Type",
        "pointerNormalFull" to "Normal Pointer",
        "pointerLassoFull" to "Selective Lasso",
        "pointerNormal" to "Normal",
        "pointerLasso" to "Lasso",
        "confirm" to "Confirm",
        "cancel" to "Cancel",
        "page" to "Page",
        "shape_rect" to "Rectangle",
        "shape_square" to "Square",
        "shape_circle" to "Circle",
        "shape_ellipse" to "Ellipse",
        "shape_line" to "Line",
        "shape_arrow" to "Arrow",
        "shape_triangle" to "Triangle",
        "shape_rightTriangle" to "Right Triangle",
        "shape_star" to "Star",
        "shape_star4" to "4-Point Star",
        "shape_star6" to "6-Point Star",
        "shape_heart" to "Heart",
        "shape_diamond" to "Diamond",
        "shape_parallelogram" to "Parallelogram",
        "shape_trapezoid" to "Trapezoid",
        "shape_pentagon" to "Pentagon",
        "shape_hexagon" to "Hexagon",
        "shape_heptagon" to "Heptagon",
        "shape_octagon" to "Octagon",
        "shape_nonagon" to "Nonagon",
        "shape_decagon" to "Decagon",
        "shape_cross" to "Cross",
        "shape_cube" to "Cube",
        "shape_cuboid" to "Cuboid",
        "shape_cylinder" to "Cylinder",
        "shape_cone" to "Cone",
        "shape_pyramid" to "Pyramid",
        "shape_sphere" to "Sphere",
        "clearPageTitle" to "Clear Page",
        "clearPageMsg" to "Are you sure you want to clear the current page?",
        "deletePageTitle" to "Delete Page",
        "deletePageMsg" to "Do you want to delete",
        "clearAllTitle" to "Clear All",
        "clearAllMsg" to "Are you sure you want to clear all pages and start over?",
        "clearSingleTitle" to "Clear Page",
        "clearSingleMsg" to "Do you want to clear all the content of Page 1?",
        "colorDefault" to "Defaults",
        "colorCustom" to "Custom",
        "toolText" to "Text",
        "toolFill" to "Fill",
        "toolBg" to "Background",
        "textOptions" to "Text Options",
        "size" to "Size",
        "save" to "Save",
        "saveTitle" to "Save Board",
        "saveMsg" to "Filename and format:",
        "ctxDup" to "Duplicate",
        "ctxFront" to "Bring to front",
        "ctxBack" to "Send to back",
        "ctxDel" to "Delete",
        "backgrounds" to "Backgrounds",
        "backgroundSettings" to "Background settings",
        "colors2" to "Colors",
        "patterns2" to "Backgrounds",
        "none" to "None"
    )

    fun of(lang: Lang): Map<String, String> = if (lang == Lang.IT) italian else english

    fun defaultLang(): Lang =
        if (java.util.Locale.getDefault().language.equals("it", ignoreCase = true)) Lang.IT else Lang.EN

    /** Tabella di traduzione usata dalla UI (chiave mancante = chiave stessa). */
    class Table(private val map: Map<String, String>) {
        operator fun get(key: String): String = map[key] ?: key
    }
}

/** Lingua corrente della UI. */
val LocalStrings = staticCompositionLocalOf { Strings.Table(Strings.of(Strings.defaultLang())) }
